[index.create]
long_about = "Creates an index at `index-uri` configured by a json file located at `index-config-uri`. The command fails if an index already exists at `index-uri` unless `overwrite` is passed. When `overwrite` is enabled, the command deletes all the files stored at `index-uri` before creating a new index. The index config defines how a document and fields it contains, are stored and indexed, see the [index config documentation](index-config.md)."

[[index.create.examples]]
name= "Create a new index with metastore in the local `metastore` folder."
command = "quickwit index create --index-config-uri ./hdfs_index_config.json --metastore-uri=file:///(pwd)/metastore"


[index.ingest]
long_about = "Indexes a dataset consisting of newline-delimited JSON objects located at `input-path` or read from *stdin*. The data is appended to the target index specified by `index-uri` unless `overwrite` is passed. `input-path` can be a file or another command output piped into stdin. Currently, only local datasets are supported. By default, tantivy's indexer will work with a heap of 2 GiB of memory, but this can be set with the `heap-size` option in the indexing_settings.resources section in the config. This does not directly reflect the overall memory usage of `quickwit index ingest`, but doubling this value should give a fair approximation."

[[index.ingest.examples]]
name = "Indexing a dataset from a file"
command = "quickwit index ingest --index-id hdfs --input-path hdfs-log.json --metastore-uri=./metastore --data-dir-path hdfs"

[[index.ingest.examples]]
name = "Indexing a dataset from stdin"
command = "cat hdfs-log.json | quickwit index ingest --index-id hdfs --metastore-uri=./metastore --data-dir-path hdfs"
